name = "LazyMaps"
uuid = "0f65a36a-af8f-424e-b067-d751494a2e7b"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
version = "0.2.0"

[deps]
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
Aqua = "0.8"
Test = "<0.0.1, 1"
TypeUtils = "1.7.1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
